### ISSUE TITLE
Allow pasting lists?

### ISSUE THREAD

**Issue by ModischFabrications** [suhankins/get-spotify-song-name#1]
The spotify desktop app offers me the option to copy all songs with CTRL+A , CTRL+S. This results in the following list of URLs: 

https://open.spotify.com/track/4s6rd2QCR3jrO81xtjlbFC
https://open.spotify.com/track/0OA00aPt3BV10qeMIs3meW
https://open.spotify.com/track/70GNKosR9Hg3aS1SPIS9ZC
https://open.spotify.com/track/2qT1uLXPVPzGgFOx4jtEuo
...

Would be nice to paste it here and get a readable list of songs. Feel free to ignore if not in the scope of this project, but it feels close enough to be a good addition.

**Comment by suhankins** [comment]
Sounds interesting, I'll look into it.

**Comment by suhankins** [comment]
After making a prototype I came to conclusion that it'd be best not to implement lists.
Main issues being:
* Spotify definitely notices me trying to request dozens of songs at a time, and promptly blocks it
* It requires a huge rewrite of the codebase

Fixing first point is technically possible, but would require even more substantial rewrite.

Was still fun looking into it, learned web components and Lit in the process.
